comment:
  image:
    repository: gryaznovart186
    tag: latest
  service:
    externalPort: 9292

post:
  image:
    repository: gryaznovart186
    tag: latest
    service:
      externalPort: 5000

ui:
  image:
    repository: gryaznovart186
    tag: latest
    service:
      externalPort: 9292
