version: '3'
services:
  fluentd:
    image: ${USERNAME}/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      elk:
  elasticsearch:
    image: elasticsearch:6.7.0
    expose:
      - 9200
    ports:
      - "9200:9200"
    networks:
      elk:

  kibana:
    image: kibana:6.7.0
    ports:
      - "5601:5601"
    networks:
      elk:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      front_net:
      back_net:
networks:
  elk:
  front_net:
  back_net:
