---
version: '3.3'
services:
  prometheus:
    image: ${USERNAME}/prometheus:latest
    ports:
      - '9090:9090'
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      monitor:

  node-exporter:
    image: prom/node-exporter:v0.15.2
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      monitor:

  post_db:
    image: mongo:${mongover}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
      monitor:

  ui:
    image: ${USERNAME}/ui:${uiver}
    ports:
      - ${UIPORT}:9292/tcp
    networks:
      front_net:
      monitor:

  post:
    image: ${USERNAME}/post:${postver}
    networks:
      front_net:
        aliases:
          - post
      back_net:
        aliases:
          - post
      monitor:

  comment:
    image: gryaznovart186/comment:${commentver}
    networks:
      front_net:
        aliases:
          - comment
      back_net:
        aliases:
          - comment
      monitor:

networks:
  front_net:
  back_net:
  monitor:

volumes:
  prometheus_data:
  post_db:
