---
version: '3.3'
services:
  post_db:
    image: mongo:${mongover}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
      monitor:

  ui:
    image: ${USERNAME}/ui:${uiver}
    ports:
      - ${UIPORT}:9292/tcp
    networks:
      front_net:
      monitor:

  post:
    image: ${USERNAME}/post:${postver}
    networks:
      front_net:
        aliases:
          - post
      back_net:
        aliases:
          - post
      monitor:

  comment:
    image: gryaznovart186/comment:${commentver}
    networks:
      front_net:
        aliases:
          - comment
      back_net:
        aliases:
          - comment
      monitor:

networks:
  front_net:
  back_net:
  monitor:

volumes:
  post_db:
