---
version: '3.3'
services:
  post_db:
    image: mongo:${mongover}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${uiver}
    ports:
      - ${UIPORT}:9292/tcp
    networks:
      front_net:
  post:
    build: ./post-py
    image: ${USERNAME}/post:${postver}
    networks:
      front_net:
        aliases:
          - post
      back_net:
        aliases:
          - post
  comment:
    build: ./comment
    image: gryaznovart186/comment:${commentver}
    networks:
      front_net:
        aliases:
          - comment
      back_net:
        aliases:
          - comment

volumes:
  post_db:

networks:
  front_net:
  back_net:
